version: '3.8'

services:
  wallet-service:
    build:
      context: .  # Текущая директория (корень проекта)
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=wallet-db
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      wallet-db:
        condition: service_healthy
    restart: unless-stopped

  wallet-db:
    image: postgres:13
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: walletpass
    ports:
      - "5432:5432"
    volumes:
      - wallet-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U walletuser -d walletdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  wallet-data: